version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    environment:
      - PLAYWRIGHT_BASE_URL=${DEPLOYMENT_URL:-http://host.docker.internal:5173}
    network_mode: host
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results