name = "visual-prompt-builder"
main = "workers/src/index.ts"
compatibility_date = "2024-06-24"

# Account settings
# account_id = "YOUR_ACCOUNT_ID" # Set via environment variable CLOUDFLARE_ACCOUNT_ID

# Build settings
[build]
command = ""
watch_paths = ["workers/src"]

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Default environment (development)
vars = { ENVIRONMENT = "development", IMAGE_PROVIDER = "replicate" }

# KV namespaces for development
[[kv_namespaces]]
binding = "CACHE"
id = "dev_cache_namespace"
preview_id = "dev_cache_preview"

[[kv_namespaces]]
binding = "SESSION"
id = "dev_session_namespace" 
preview_id = "dev_session_preview"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "dev_rate_limit_namespace"
preview_id = "dev_rate_limit_preview"

[[kv_namespaces]]
binding = "IMAGE_CACHE"
id = "dev_image_cache_namespace"
preview_id = "dev_image_cache_preview"

# Staging environment
[env.staging]
name = "visual-prompt-builder-staging"
vars = { ENVIRONMENT = "staging", IMAGE_PROVIDER = "replicate" }

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "staging_cache_namespace"

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "staging_session_namespace"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "staging_rate_limit_namespace"

[[env.staging.kv_namespaces]]
binding = "IMAGE_CACHE"
id = "staging_image_cache_namespace"

# Production environment
[env.production]
name = "visual-prompt-builder"
vars = { ENVIRONMENT = "production", IMAGE_PROVIDER = "replicate" }

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "ac4cfe9a60374e0982097a6dda928044"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "bc2a774a46324cdab41089aa659ece23"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "f4948d4c905944cbbd95aa798985179a"

[[env.production.kv_namespaces]]
binding = "IMAGE_CACHE"
id = "production_image_cache_namespace"

# Routes (will be configured later)
# [[env.production.routes]]
# pattern = "api.example.com/*"
# zone_name = "example.com"

# Secrets (set via wrangler secret)
# - TRANSLATION_API_KEY
# - LOGFLARE_API_KEY (optional)

# Pages configuration
pages_build_output_dir = "frontend/dist"