name = "visual-prompt-builder-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "4b2c535505b7438ab4d382e170f3758e"
preview_id = "0214ee29e371415a9fa6ef0a9f229509"

[[kv_namespaces]]
binding = "SESSION"
id = "aa2e97aef4e14eb7a39872875b59ec74"
preview_id = "de725a4a38fc43f28cca9afd16c4d5f9"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "0e0422b2b9f14a99b40adcb4906441e5"
preview_id = "d0a6740231fd4448b5e84313dbea0129"

[[kv_namespaces]]
binding = "IMAGE_CACHE"
id = "83ea1a9180c84ed4a23b325583dbe737"
preview_id = "14ecb1acbc0348018c09a34efb215c7e"

# R2 Bucket
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "prompt-builder"
preview_bucket_name = "prompt-builder-dev"

# 環境変数（開発環境）
[vars]
ENVIRONMENT = "development"
IMAGE_PROVIDER = "replicate"
R2_CUSTOM_DOMAIN = "https://image-dev.kantanprompt.com"
R2_S3_API_DEV = "https://1b154d8dab68e47be1d8dc7734f1d802.r2.cloudflarestorage.com/prompt-builder-dev"
R2_S3_API_PROD = "https://1b154d8dab68e47be1d8dc7734f1d802.r2.cloudflarestorage.com/prompt-builder"

# 本番環境用の設定
[env.production]
routes = [
  { pattern = "api.kantanprompt.com", custom_domain = true }
]
vars = { ENVIRONMENT = "production", IMAGE_PROVIDER = "replicate", R2_CUSTOM_DOMAIN = "https://image.kantanprompt.com", R2_S3_API_DEV = "https://1b154d8dab68e47be1d8dc7734f1d802.r2.cloudflarestorage.com/prompt-builder-dev", R2_S3_API_PROD = "https://1b154d8dab68e47be1d8dc7734f1d802.r2.cloudflarestorage.com/prompt-builder" }

# 本番環境用のKV Namespaces
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "ac4cfe9a60374e0982097a6dda928044"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "bc2a774a46324cdab41089aa659ece23"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "f4948d4c905944cbbd95aa798985179a"

[[env.production.kv_namespaces]]
binding = "IMAGE_CACHE"
id = "8c0fea232e374471a8778c1d9bcbba7a"

# 本番環境用のR2 Bucket
[[env.production.r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "prompt-builder"

# シークレット（実際の値は wrangler secret put で設定）
# IMAGE_API_KEY = "your-api-key"
# TRANSLATION_API_KEY = "your-translation-api-key"
# R2_ACCESS_KEY_ID = "your-r2-access-key"
# R2_SECRET_ACCESS_KEY = "your-r2-secret-key"