name: Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  schedule:
    # 毎週月曜日の午前9時（UTC）に実行
    - cron: '0 9 * * 1'

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml

      - name: Upload SARIF report
        if: failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  trufflehog-scan:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Skip if it's a PR from the same commit (no diff to scan)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.sha != github.event.pull_request.base.sha

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog (Git Diff)
        id: trufflehog-git
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.before || github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha || github.event.after || 'HEAD' }}
          extra_args: --only-verified
        continue-on-error: true

      - name: Run TruffleHog (Filesystem)
        if: steps.trufflehog-git.conclusion != 'success'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified --filesystem
        continue-on-error: true

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate || true

      - name: Run Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
